-- DESASOCIAR  PERMISO PLANTA_MODIFICAR DE ROL DE CONSULTA DE DESPACHO IDEAL
DELETE FROM controlAcceso.RolPermiso WHERE rolID = 11 AND permisoID = 7;
GO

-- DESASOCIAR  PERMISO PLANTA_MODIFICAR DE ROL DE CONSULTA DE DESPACHO IDEAL
DELETE FROM controlAcceso.RolPermiso WHERE rolID = 11 AND permisoID = 126;
GO

-- DESASOCIAR  PERMISO GRUPO_CORREO_CREAR DE ROL DE CONSULTA DE DESPACHO IDEAL
DELETE FROM controlAcceso.RolPermiso WHERE rolID = 11 AND permisoID = 116;
GO

-- DESASOCIAR  PERMISO GRUPO_CORREO_MODIFICAR DE ROL DE CONSULTA DE DESPACHO IDEAL
DELETE FROM controlAcceso.RolPermiso WHERE rolID = 11 AND permisoID = 117;
GO

SET IDENTITY_INSERT controlAcceso.RolPermiso ON

--- PERMISO PLANTA_VER
INSERT INTO [controlAcceso].[RolPermiso](rolPermisoID,rolID,permisoID,fechaInicio,fechaFinal)
VALUES (669,10,6,SYSDATETIMEOFFSET()  AT TIME ZONE 'SA Pacific Standard Time',null)

---PERMISO PLANTA_MODIFICAR
INSERT INTO [controlAcceso].[RolPermiso](rolPermisoID,rolID,permisoID,fechaInicio,fechaFinal)
VALUES (670,10,7,SYSDATETIMEOFFSET()  AT TIME ZONE 'SA Pacific Standard Time',null)

SET IDENTITY_INSERT controlAcceso.RolPermiso OFF