package com.xm.clavesecreto.modelo.enums;

import com.xm.dominio.enums.ClaveSecretoInterfazEnum;

public enum ClaveSecretoEnum implements ClaveSecretoInterfazEnum {

	AUTENTICACION_APLICACION_TOKEN("AUTENTICACION-APLICACION-TOKEN", "AUTENTICACION_APLICACION_TOKEN"),
	AUTENTICACION_CORREO("AUTENTICACION-CORREO", "AUTENTICACION_CORREO"),
	AUTENTICACION_NOMBRE("AUTENTICACION-NOMBRE", "AUTENTICACION_NOMBRE"),
	AUTENTICACION_NOMBRE_COMPLETO("AUTENTICACION-NOMBRE-COMPLETO", "AUTENTICACION_NOMBRE_COMPLETO"),
	AUTENTICACION_OBJECTO_ID("AUTENTICACION-OBJECTO-ID", "AUTENTICACION_OBJECTO_ID"),
	AUTENTICACION_CLIENT_ID_USUARIO("AUTENTICACION-CLIENT-ID-USUARIO", "AUTENTICACION_CLIENT_ID_USUARIO"),
	AUTENTICACION_CLIENT_ID_TECNICO("AUTENTICACION-CLIENT-ID-TECNICO", "AUTENTICACION_CLIENT_ID_TECNICO"),
	TOKEN_CLAVE_FIRMADO("TOKEN-CLAVE-FIRMADO", "TOKEN_CLAVE_FIRMADO"), AUTHORITY("AUTHORITY", "AUTHORITY"),
	CLIENT_ID("CLIENT-ID", "CLIENT_ID"), CLIENT_SECRET("CLIENT-SECRET", "CLIENT_SECRET"),
	URL_LLAVES_PUBLICAS("URL-LLAVES-PUBLICAS", "URL_LLAVES_PUBLICAS"),
	TOKEN_AUDIENCE_APPLICATION("TOKEN-AUDIENCE-APPLICATION", "TOKEN_AUDIENCE_APPLICATION"),
	OCP_APIM_SUSCRIPTION_KEY("OCP-APIM-SUSCRIPTION-KEY", "OCP_APIM_SUSCRIPTION_KEY");

	private final String clave;
	private final String secreto;

	ClaveSecretoEnum(String clave, String secreto) {
		this.secreto = secreto;
		this.clave = clave;
	}

	public String getSecreto() {
		return secreto;
	}

	public String getClave() {
		return clave;
	}
}
