package com.xm.autenticacion.servicio.testdatabuilder;

import com.xm.dominio.token.modelo.dto.DtoRespuestaAutenticacion;

public class DtoRespuestaAutenticacionTestDataBuilder {

	private String token;
	private String refreshToken;


	public DtoRespuestaAutenticacionTestDataBuilder() {
		this.token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IlNpbXBPcGVyYTAxIiwiSWRPYmpldG8iOiI5MWY2NDNjYS00NWU3LTQzNWEtYjE2Ni0yMjI0YjI2ODUzNzIiLCJJZFVzdWFyaW8iOiIzMzYiLCJFbWFpbCI6IjEwMzU1MjQ1MkBYTS5DT00uQ08iLCJSb2xlcyI6IlNPIC0gRGVzcGFjaG8sU08gLSBEZXNwYWNob0FkbWluIiwiTm9tYnJlQ29tcGxldG8iOiJTaW1wT3BlcmEwMSIsIklkQ29tcGFuaWFzIjoiIiwiVG9rZW5BcGxpY2FjaW9uIjoiM2VhNzkzZWYtNmFkYy00MzJlLWFlMjYtMjhiZjY5MWQ2NjM0IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjpbIlNPIC0gRGVzcGFjaG8iLCJTTyAtIERlc3BhY2hvQWRtaW4iXSwiZXhwIjoxNjYyMDM2NTQxL";
		this.refreshToken = "OiIXV83MeS5/evXHgkFlhnRXA33QmOCyrq9ebbUG4ck=";
	}

	public DtoRespuestaAutenticacion construir() {
		return new DtoRespuestaAutenticacion(token, refreshToken);
	}
}
